import QtQuick
import Quickshell
import Quickshell.Io
import "Model.js" as Model

Item {
  id: root
  property var shell: null
  property string omarchyPath: ""
  property var manifest: null
  readonly property string home: Quickshell.env("HOME")
  readonly property string stateDir: home + "/.local/state/omarchy/zakarch.borders"
  readonly property string statePath: stateDir + "/settings.json"
  readonly property string generatedPath: stateDir + "/generated.lua"

  property int paletteIndex: 0
  property int rounding: 8
  property int borderSize: 2
  property int windowGap: 2
  property bool shine: true
  property int cycleSeconds: 3
  property bool loaded: false
  property string status: "Starting…"
  property bool syncingShellAppearance: false

  function safePalette() { return Model.palettes[Math.max(0, Math.min(paletteIndex, Model.palettes.length - 1))] }
  function rgba(hex) {
    var h = String(hex).replace("#", "").toUpperCase()
    return "rgba(" + h + "EE)"
  }
  function luaColor(hex) { return "\"" + rgba(hex) + "\"" }
  function luaGradient(colors) {
    return "{ colors = {" + colors.map(luaColor).join(", ") + "}, angle = 45 }"
  }
  function runtimeConfig() {
    var p = safePalette()
    var active = shine ? luaGradient(p.active) : luaColor(p.active[0])
    return "hl.config({ general = { border_size = " + borderSize
      + ", gaps_in = " + windowGap
      + ", gaps_out = " + windowGap
      + ", col = { active_border = " + active
      + ", inactive_border = " + luaColor(p.inactive)
      + " } }, decoration = { rounding = " + rounding + " } })"
  }
  function applyLegacyStep(step) {
    var commands = [
      ["general:col.active_border", shine ? safePalette().active.map(function(color) { return rgba(color) }).join(" ") + " 45deg" : rgba(safePalette().active[0])],
      ["general:col.inactive_border", rgba(safePalette().inactive)],
      ["general:border_size", String(borderSize)],
      ["general:gaps_in", String(windowGap)],
      ["general:gaps_out", String(windowGap)],
      ["decoration:rounding", String(rounding)]
    ]
    if (step >= commands.length) return
    legacyStep.command = ["hyprctl", "keyword", commands[step][0], commands[step][1]]
    legacyStep.running = true
  }
  function clampNumber(value, fallback, min, max) {
    var n = Number(value)
    if (!isFinite(n)) n = fallback
    return Math.max(min, Math.min(n, max))
  }
  function applyShellAppearance() {
    if (syncingShellAppearance) return
    syncingShellAppearance = true
    var p = safePalette()
    var values = {}
    for (var key in Color.shellValues) values[key] = Color.shellValues[key]
    var border = shine ? p.active.join(" ") + " 45deg" : p.active[0]
    var sections = ["popups", "tooltip", "notifications", "menu"]
    for (var i = 0; i < sections.length; i++) {
      values[sections[i] + ".border"] = border
      values[sections[i] + ".border-width"] = String(borderSize)
    }
    Color.shellValues = values
    Style.cornerRadius = rounding
    syncingShellAppearance = false
  }
  function generatedText() {
    var p = safePalette()
    var active = shine ? luaGradient(p.active) : luaColor(p.active[0])
    var inactive = luaColor(p.inactive)
    return "-- Generated by zakarch.borders. Edit through Border Studio.\n"
      + "hl.config({ general = { border_size = " + borderSize + ", gaps_in = " + windowGap + ", gaps_out = " + windowGap + ", col = { active_border = " + active
      + ", inactive_border = " + inactive + " } } })\n"
      + "hl.config({ decoration = { rounding = " + rounding + " } })\n"
  }
  function apply() {
    if (!loaded) return
    generatedFile.setText(generatedText())
    applyShellAppearance()
    runtimeApply.command = ["hyprctl", "eval", runtimeConfig()]
    runtimeApply.running = true
    saveTimer.restart()
    status = "Applied " + safePalette().name + " · " + (shine ? "shining" : "solid") + " · " + borderSize + " px"
  }
  function save() { stateFile.setText(JSON.stringify({ version: 1, paletteIndex: paletteIndex, rounding: rounding, borderSize: borderSize, windowGap: windowGap, shine: shine, cycleSeconds: cycleSeconds }, null, 2) + "\n") }
  function load(raw, replaceLoaded) {
    if (loaded && !replaceLoaded) return
    var data = {}
    try { data = JSON.parse(raw || "{}") } catch (e) {}
    paletteIndex = clampNumber(data.paletteIndex, 0, 0, Model.palettes.length - 1)
    rounding = clampNumber(data.rounding, 8, 0, 32)
    borderSize = clampNumber(data.borderSize, 2, 0, 10)
    windowGap = clampNumber(data.windowGap, 2, 0, 64)
    shine = data.shine === undefined ? true : data.shine === true
    cycleSeconds = clampNumber(data.cycleSeconds, 3, 0, 3600)
    loaded = true
    apply()
    syncCycleTimer()
  }
  function choosePalette(index) { paletteIndex = index; apply() }
  function setRounding(value) { rounding = value; apply() }
  function setBorderSize(value) { borderSize = value; apply() }
  function setWindowGap(value) { windowGap = value; apply() }
  function setShine(value) { shine = value; apply() }
  function setCycle(value) { cycleSeconds = value; syncCycleTimer(); apply() }
  function syncCycleTimer() {
    if (loaded && cycleSeconds > 0) cycleTimer.start()
    else cycleTimer.stop()
  }

  FileView { id: stateFile; path: root.statePath; watchChanges: false; atomicWrites: true; printErrors: false; onLoaded: root.load(text(), true); onLoadFailed: root.load("", true) }
  FileView { id: generatedFile; path: root.generatedPath; watchChanges: false; atomicWrites: true; printErrors: false }
  Connections {
    target: Color
    function onShellValuesChanged() {
      if (root.loaded && !root.syncingShellAppearance) root.applyShellAppearance()
    }
  }
  Process {
    id: ensureDir
    command: ["mkdir", "-p", root.stateDir]
    onExited: stateFile.reload()
  }
  Timer {
    id: startupLoad
    interval: 1000
    repeat: false
    onTriggered: {
      if (!root.loaded) root.load(stateFile.text(), false)
    }
  }
  Process {
    id: runtimeApply
    onExited: function(exitCode) {
      if (exitCode !== 0) {
        legacyStepIndex = 0
        applyLegacyStep(legacyStepIndex)
      }
    }
  }
  property int legacyStepIndex: 0
  Process {
    id: legacyStep
    onExited: function(exitCode) {
      if (exitCode !== 0) console.warn("Border Studio: hyprctl keyword failed with code " + exitCode)
      legacyStepIndex++
      applyLegacyStep(legacyStepIndex)
    }
  }
  Timer { id: saveTimer; interval: 250; repeat: false; onTriggered: root.save() }
  Timer {
    id: cycleTimer
    repeat: true
    interval: Math.max(1000, root.cycleSeconds * 1000)
    onTriggered: root.choosePalette((root.paletteIndex + 1) % Model.palettes.length)
  }
  onPaletteIndexChanged: if (loaded) saveTimer.restart()
  onRoundingChanged: if (loaded) saveTimer.restart()
  onBorderSizeChanged: if (loaded) saveTimer.restart()
  onWindowGapChanged: if (loaded) saveTimer.restart()
  onShineChanged: if (loaded) saveTimer.restart()
  onCycleSecondsChanged: { if (loaded) saveTimer.restart(); syncCycleTimer() }
  Component.onCompleted: {
    // Apply defaults immediately; loading a state file must never gate startup.
    load("")
    ensureDir.running = true
    startupLoad.start()
  }
}
